name: "Deploy to GH Pages"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm

      - name: Install
        run: npm install

      - name: Run deploy script
        run: ./deploy.sh
